# This file contains the core logic for the chatbot, including loading environment variables and generating responses using the Google Generative AI model.
# It defines the `chatbot_response` function, which takes user input and returns a response generated by the model. The function loads the API key from the .env file and uses it to initialize the language model before invoking it with the user's input.


# External libs
from langchain_google_genai import ChatGoogleGenerativeAI

# Default Python package Imports
import os

# Internal imports
from dotenv import load_dotenv
from config import PERSONALITY_PROMPT, MODEL_NAME, MAX_TOKENS, TEMPERATURE, STREAMING


load_dotenv()


def get_llm():

    model = MODEL_NAME

    # 2. Access the variable (LangChain often looks for GOOGLE_API_KEY automatically)
    google_api_key = os.getenv("GOOGLE_API_KEY")

    # max_output_tokens: Limits the response length
    max_output_tokens = MAX_TOKENS
    temperature = TEMPERATURE
    streaming = STREAMING

    llm = ChatGoogleGenerativeAI(
        model=model,
        google_api_key=google_api_key,
        max_output_tokens=max_output_tokens,  # Limits response length
        temperature=temperature,  # Creative but controlled
        streaming=streaming,  # Enables real-time responses
    )
    return llm


def get_ai_personality():

    personality_prompt = PERSONALITY_PROMPT
    return personality_prompt


# def chatbot_response(user_input):

# llm = get_llm()
# personality = ai_personality()


# def chatbot_response(user_input):

#     # 1. Load the variables from the .env file into the system environment
#


#     api_key = os.getenv("GOOGLE_API_KEY")

#     llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=api_key)
#     response = llm.invoke(user_input)
#     return response.content
